window.dashboardData = {
  "header": {
    "title": "苏州顶津 - 资金预算与工程进度综合看板",
    "subtitle": "实时监控资金分配、施工与规划全生命周期",
    "date": "2026-08-15",
    "user": "管理员"
  },
  "kpi": {
    "totalBudget": "2.3",
    "totalBudgetUnit": "亿元",
    "actualSpend": "0.8",
    "actualSpendUnit": "亿元",
    "executionRate": "68.0%",
    "overallProgress": 65,
    "warningStatus": "暂无严重超支",
    "warningSubtext": "各项预算偏差处于正常红线内"
  },
  "chart": {
    "labels": [
      "土建",
      "设备",
      "模具",
      "工程",
      "其他"
    ],
    "budgets": [
      500,
      500,
      500,
      300,
      200
    ],
    "actuals": [
      120,
      150,
      100,
      100,
      14
    ]
  },
  "projectsData": [
    {
      "name": "关于苏州厂品管部检验科门改造小工程",
      "progress": "2026-01-15",
      "status": "已验收未开票",
      "dept": "品管",
      "cost": "0.4414",
      "supplier": "安徽业峰建筑工程有限公司",
      "manager": "陈志强",
      "Categories": "维修费",
      "Notes": "4414.41已通知开票"
    },
    {
      "name": " 苏州顶津110KV电力投运后谐波治理",
      "progress": "2026-01-06",
      "status": "已验收未开票",
      "dept": "厂务",
      "cost": "149",
      "supplier": "苏州华安普电力科技有限公司",
      "manager": "陈天飞",
      "Categories": "固定资产",
      "Notes": "验收签呈已上未核准"
    },
    {
      "name": "关于苏州厂制造一处星巴克灌装科及调配D58审核自检自查改善事宜",
      "progress": "2025-04-30",
      "status": "已验收未开票",
      "dept": "星巴克",
      "cost": "6.918",
      "supplier": "杭州利川机电有限公司",
      "manager": "王天禄",
      "Categories": "维修费",
      "Notes": "62045已通知开票"
    },
    {
      "name": "关于苏州厂制造二处无菌六线正压房更换过滤器及部分改善工程事宜",
      "progress": "2026-03-27",
      "status": "已验收未开票",
      "dept": "制二",
      "cost": "2.44",
      "supplier": "苏州振佑机电科技有限公司",
      "manager": "李双",
      "Categories": "维修费",
      "Notes": "24415已通知开票"
    },
    {
      "name": "关于苏州厂制造二处无菌五线风干机移位及部分改善工程事宜",
      "progress": "2026-05-31",
      "status": "已验收未开票",
      "dept": "制二",
      "cost": "1.3",
      "supplier": "杭州利川机电有限公司",
      "manager": "李双",
      "Categories": "维修费",
      "Notes": "12960.4已通知开票"
    },
    {
      "name": "关于苏州厂制造一处D58审核及511A+参观工程公建类整改申请事宜",
      "progress": "2025-04-25",
      "status": "已验收未开票",
      "dept": "星巴克",
      "cost": "7.3904",
      "supplier": "权璟建设工程（大连）有限公司",
      "manager": "王天禄",
      "Categories": "维修费",
      "Notes": "72273.67"
    },
    {
      "name": "关于三车间办公室顶部吊顶申请维修事宜",
      "progress": "2025-11-05",
      "status": "已验收未开票",
      "dept": "制二",
      "cost": "0.93",
      "supplier": "杭州莫其名装饰有限公司",
      "manager": "徐杨",
      "Categories": "维修费"
    },
    {
      "name": "关于无菌五线新增第二台贴标机配套物料输送带改造工程议价申请事宜",
      "progress": "2024-11-19",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "51",
      "supplier": "阳兴造机（东莞）有限公司",
      "manager": "李双",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州厂无菌四、五线物料输送带改造调试申请事宜",
      "progress": "2026-01-19",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "6.2",
      "supplier": "阳兴造机（东莞）有限公司",
      "manager": "陈臣",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州厂二、三车间自来水换热节能改善立项申请事宜",
      "progress": "2025-07-24",
      "status": "已完工未验收",
      "dept": "厂务",
      "cost": "145",
      "supplier": "苏州振佑机电科技有限公司",
      "manager": "孙士友",
      "Categories": "固定资产",
      "Notes": "8月验收"
    },
    {
      "name": "关于一车间TP线6连包设备移位改造邀标申请事宜",
      "progress": "2025-10-27",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "76.83",
      "supplier": "北京永创通达机械设备有限公司",
      "manager": "乔欣欣",
      "Categories": "固定资产",
      "Notes": "增项中"
    },
    {
      "name": "关于PH9.0及无菌五线施工配套安装工程隔断防护申请事宜",
      "progress": "2026-01-20",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "19.624",
      "supplier": "陕西亿谦建设工程有限公司",
      "manager": "朱鹏鹏",
      "Categories": "固定资产"
    },
    {
      "name": "关于连廊输送增加码垛机配套安装工程申请",
      "progress": "2025-12-30",
      "status": "已完工未验收",
      "dept": "设备",
      "cost": "9.1211",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "杨硕",
      "Categories": "固定资产",
      "Notes": "增项中"
    },
    {
      "name": "关于一车间充填一科西德乐水线罐装机正压罩改造升级申请事宜",
      "progress": "2025-02-25",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "25.7294",
      "supplier": "河南中润实验室工程有限公司",
      "manager": "朱鹏鹏",
      "Categories": "固定资产"
    },
    {
      "name": "关于一车间充填一科二线、四线贴标机视检机改造升级申请事宜",
      "progress": "2025-03-11",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "14.8",
      "supplier": "天津优海云图科技有限公司",
      "manager": "朱鹏鹏",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州顶津制造一处13水站增加PH联动工程改造申请事宜",
      "progress": "2025-10-21",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "9.22",
      "supplier": "环亚（广州）环境科技有限公司",
      "manager": "王振友",
      "Categories": "维修费",
      "Notes": "存在PH联动问题，需供应商到厂调试效果满足使用后再验收"
    },
    {
      "name": "关于康仁苏州康饮28口产线“可尔必思系列” 新瓶型（风轨改造）招标事宜",
      "progress": "2025-12-02",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "59.9",
      "supplier": "上海平运机械设备有限公司",
      "manager": "徐杨",
      "Categories": "固定资产",
      "Notes": "调试中，未达到使用要求，暂不验收"
    },
    {
      "name": "关于苏州顶津制造一处调配科V4调配系统增加果糖添加改造工程申请事宜",
      "progress": "2026-01-10",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "5.05",
      "supplier": "杭州展博机械有限公司",
      "manager": "王振友",
      "Categories": "固定资产",
      "Notes": "测试中，无问题点后验收，下月验收"
    },
    {
      "name": "关于制造一处车间地面GMP改善工程申请",
      "progress": "2026-02-24",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "28.6986",
      "supplier": "宣城市瑞天建筑工程有限公司",
      "manager": "赵春军",
      "Categories": "维修费",
      "Notes": "本月验收"
    },
    {
      "name": "关于苏州厂无菌五线增加外箱覆膜机及后段重新布局改造申请事宜-----输送带改造",
      "progress": "2025-12-01",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "160",
      "supplier": "象山大宇机械设备有限公司",
      "manager": "李双",
      "Categories": "固定资产",
      "Notes": "设备稳定后验收"
    },
    {
      "name": "关于无菌4、5线包装机对换改造申请事宜---（为PH9.0和无菌五线后段升级改造配套工程）",
      "progress": "2025-12-04",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "27.15",
      "supplier": "彬台自动化设备（苏州）有限公司",
      "manager": "陈臣",
      "Categories": "固定资产"
    },
    {
      "name": "关于无菌四线包装机改面对面立项申请事宜",
      "progress": "2026-01-22",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "52",
      "supplier": "象山大宇机械设备有限公司",
      "manager": "陈臣",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州顶津制造一处调配桶搅拌漏液工程维修申请事宜",
      "progress": "2026-01-05",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "8.0702",
      "supplier": "扬州市新海食品机械有限公司",
      "manager": "王振友",
      "Categories": "维修费",
      "Notes": "测试中，无问题点后验收；预计下月低验收"
    },
    {
      "name": "关于三车间瓶胚直连配套安装工程申请事宜",
      "progress": "2026-04-08",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "1.86",
      "supplier": "苏州玥祥建筑工程有限公司",
      "manager": "徐杨",
      "Categories": "固定资产",
      "Notes": "7月完成验收"
    },
    {
      "name": "关于制造二处旋盖机保养配套龙门架工程申请事宜",
      "progress": "2026-05-31",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "1.82",
      "supplier": "杭州利川机电有限公司",
      "manager": "李双",
      "Categories": "维修费"
    },
    {
      "name": "关于一车间水3线喷码机移位工程申请事宜",
      "progress": "2026-05-15",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "2.38",
      "supplier": "杭州利川机电有限公司",
      "manager": "朱鹏鹏",
      "Categories": "维修费"
    },
    {
      "name": "关于三车间溶糖、排渣间地面维修申请招标事宜",
      "progress": "2025-09-26",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "9.801",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "陈赏",
      "Categories": "维修费",
      "Notes": "8月验收"
    },
    {
      "name": "关于三车间废气处理系统邀标作业事宜",
      "progress": "2026-02-13",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "99.12",
      "supplier": "昆士通环保设备（昆山）有限公司",
      "manager": "卞清泉",
      "Categories": "固定资产"
    },
    {
      "name": "关于一车间风幕机安装工程申请事宜",
      "progress": "2026-04-17",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "6.6",
      "supplier": "苏州驻阳机电设备工程有限公司",
      "manager": "王振友",
      "Categories": "维修费",
      "Notes": "测试中，无问题点后验收，"
    },
    {
      "name": "关于一车间电柜通风及加热炉维修恢复",
      "progress": "2026-04-27",
      "status": "已完工未验收",
      "dept": "星巴克",
      "cost": "1.81",
      "supplier": "苏州振佑机电科技有限公司",
      "manager": "朱鹏鹏",
      "Categories": "维修费"
    },
    {
      "name": "关于瓶胚1线二级电柜断路器更换改造招标事宜",
      "progress": "2026-06-29",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "1.54",
      "supplier": "苏州芃盛电力技术服务有限公司",
      "manager": "赵春军",
      "Categories": "维修费",
      "Notes": "已完成，评估结果验收"
    },
    {
      "name": "关于苏州厂品管部制程一科维修小工程",
      "progress": "2026-02-02",
      "status": "已完工未验收",
      "dept": "品管",
      "cost": "8.39",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "周伟",
      "Categories": "维修费"
    },
    {
      "name": "茶叶拼配实验室土建工程招标申请",
      "progress": "2026-02-10",
      "status": "已完工未验收",
      "dept": "茶露",
      "cost": "197.6818",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "马博",
      "Categories": "固定资产"
    },
    {
      "name": "关于茶叶拼配实验室土建工程增项邀标申请事宜",
      "progress": "2026-04-17",
      "status": "已完工未验收",
      "dept": "茶露",
      "cost": "44.11",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "马博",
      "Categories": "固定资产"
    },
    {
      "name": "关于厂区路灯主电缆更换及浓水排口改造申请事宜",
      "progress": "2026-04-25",
      "status": "已完工未验收",
      "dept": "厂务",
      "cost": "4.5",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "陈天飞",
      "Categories": "维修费"
    },
    {
      "name": "苏州顶津厂务外围损坏门更换修缮工程招标申请",
      "progress": "2026-03-30",
      "status": "已完工未验收",
      "dept": "厂务",
      "cost": "8.48",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "孙士友",
      "Categories": "维修费",
      "Notes": "增项中"
    },
    {
      "name": "关于苏州顶津二车间消防管网及自来水管网渗漏抢修申请事宜",
      "progress": "2026-06-30",
      "status": "已完工未验收",
      "dept": "厂务",
      "cost": "4.7",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "陈天飞",
      "Categories": "维修费"
    },
    {
      "name": "关于热充二线330增加膜包机配套安装工程邀标申请事宜（流标重新申请）",
      "progress": "2026-04-11",
      "status": "已完工未验收",
      "dept": "设备",
      "cost": "40.28",
      "supplier": "武汉鑫得盛机电设备有限公司",
      "manager": "刘传海",
      "Categories": "固定资产",
      "Notes": "目前在走增项中，结束后走验收流程"
    },
    {
      "name": "关于污水系统二三期液碱提升泵加药系统改造申请事宜",
      "progress": "2026-05-15",
      "status": "已完工未验收",
      "dept": "厂务",
      "cost": "6.99",
      "supplier": "武汉鑫得盛机电设备有限公司",
      "manager": "陈天飞",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州顶津内屋面&钢梁改善项目申请招标事宜",
      "progress": "2026-06-22",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "27",
      "supplier": "武汉鑫得盛机电设备有限公司",
      "manager": "李双",
      "Categories": "其他资产"
    },
    {
      "name": "关于苏州顶津热充一线正压房玻璃破损更换工程申请",
      "progress": "2026-05-31",
      "status": "已完工未验收",
      "dept": "热充",
      "cost": "0.41",
      "supplier": "武汉鑫得盛机电设备有限公司",
      "manager": "杨华超",
      "Categories": "维修费",
      "Notes": "计划8月验收"
    },
    {
      "name": "关于苏州顶津制造一处调配科通道天花板清洁更换申请事宜",
      "progress": "2026-07-24",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "1.9",
      "supplier": "宣城市瑞天建筑工程有限公司",
      "manager": "王振友",
      "Categories": "维修费"
    },
    {
      "name": "关于无菌5、6线及PH9.0改造配套安装工程邀标申请事宜---（公建配套安装工程）",
      "progress": "2025-12-09",
      "status": "已完工未验收",
      "dept": "制二",
      "cost": "83.3898",
      "supplier": "杭州利川机电有限公司",
      "manager": "李双",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州厂热充二线冷瓶机热能回收改造邀标申请事宜",
      "progress": "2026-02-24",
      "status": "已完工未验收",
      "dept": "热充",
      "cost": "99.8",
      "supplier": "宋泰工程技术（杭州）有限公司",
      "manager": "杨华超",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州厂热充二线生产330产品新增输送带改造邀标申请事宜",
      "progress": "2026-01-26",
      "status": "已完工未验收",
      "dept": "热充",
      "cost": "51",
      "supplier": "北京永创通达机械设备有限公司",
      "manager": "杨华超",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州顶津厂区外围设施改善工程项目立项申请事宜",
      "progress": "2026-03-30",
      "status": "已完工未验收",
      "dept": "厂务",
      "cost": "19.5",
      "supplier": "安徽业峰建筑工程有限公司",
      "manager": "郑胤煊",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州顶津热充二线330规格运膜通道改造工程申请",
      "progress": "2026-05-25",
      "status": "已完工未验收",
      "dept": "热充",
      "cost": "3.52",
      "supplier": "苏州驻阳机电设备工程有限公司",
      "manager": "杨华超",
      "Categories": "固定资产",
      "Notes": "有两处需要改善，计划8月验收"
    },
    {
      "name": "关于制造一处充填三科现场品质改善工程议价申请事宜",
      "progress": "2026-06-08",
      "status": "已完工未验收",
      "dept": "制一",
      "cost": "9.55",
      "supplier": "杭州利川机电有限公司",
      "manager": "杨硕",
      "Categories": "维修费",
      "Notes": "8月验收"
    },
    {
      "name": "关于热充车间通风管改造工程申请",
      "progress": "2026-07-06",
      "status": "已完工未验收",
      "dept": "热充",
      "cost": "3.36",
      "supplier": "苏州振佑机电科技有限公司 ",
      "manager": "杨华超",
      "Categories": "维修费",
      "Notes": "7月份已经开始使用，计划8月验收"
    },
    {
      "name": "关于苏州厂热充二线生产330产品新增膜包机邀标申请事宜",
      "progress": "2026-02-04",
      "status": "已完工未验收",
      "dept": "热充",
      "cost": "113.8",
      "supplier": "北京永创通达机械设备有限公司",
      "manager": "杨华超",
      "Categories": "固定资产"
    },
    {
      "name": "苏州顶津工厂二三车间屋面百叶窗修缮工程招标申请",
      "progress": "2026-05-18",
      "status": "已开工未完成",
      "dept": "厂务",
      "cost": "6.29",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "孙士友",
      "Categories": "维修费"
    },
    {
      "name": "关于三车间墙面申请维修事宜",
      "progress": "2026-01-15",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "2.25",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "徐杨",
      "Categories": "维修费",
      "Notes": "未完成"
    },
    {
      "name": "26年苏州顶津土建类维修年度标项目申请事宜",
      "progress": "2026-03-30",
      "status": "已开工未完成",
      "dept": "厂务",
      "cost": "18.74",
      "supplier": "安徽业峰建筑工程有限公司",
      "manager": "郑胤煊",
      "Categories": "维修费",
      "Notes": "季度量已达标，准备验收"
    },
    {
      "name": "关于苏州顶津仓储处改善工程申请事宜",
      "progress": "2026-05-25",
      "status": "已开工未完成",
      "dept": "仓储",
      "cost": "5.39",
      "supplier": "苏州驻阳机电设备工程有限公司",
      "manager": "苏文彬",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州厂一车间制程留样室电梯维修保养事宜",
      "progress": "2025-10-16",
      "status": "已开工未完成",
      "dept": "品管",
      "cost": "0.5242",
      "supplier": "苏州鑫安达电梯工程有限公司",
      "manager": "周伟",
      "Categories": "维修费",
      "Notes": "合同期限一年，2026.10月到期"
    },
    {
      "name": "关于苏州厂无菌五线增加外箱覆膜机及后段重新布局改造--外箱覆膜机购买邀标申请事宜",
      "progress": "2025-12-02",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "106",
      "supplier": "北京永创通达机械设备有限公司",
      "manager": "李双",
      "Categories": "固定资产",
      "Notes": "目前存在问题处理完验收"
    },
    {
      "name": "关于苏州顶津制造一处充填一科康水二线安装提拔视检机申请事宜",
      "progress": "2025-03-20",
      "status": "已开工未完成",
      "dept": "制一",
      "cost": "2.5",
      "supplier": "天津优海云图科技有限公司",
      "manager": "朱鹏鹏",
      "Categories": "固定资产"
    },
    {
      "name": "关于制造一处玻璃瓶线充填机主齿轮龙门架搭建申请事宜",
      "progress": "2025-11-26",
      "status": "已开工未完成",
      "dept": "制一",
      "cost": "0.9337",
      "supplier": "沈阳工业安装工程股份有限公司",
      "manager": "王天禄",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州厂制造一处调配科调配区工程改造申请事宜",
      "progress": "2025-02-11",
      "status": "已开工未完成",
      "dept": "制一",
      "cost": "9.9682",
      "supplier": "杭州利川机电有限公司",
      "manager": "王振友",
      "Categories": "维修费",
      "Notes": "施工项目还未完成"
    },
    {
      "name": "关于三车间调配区域隔断&风管改造申请招标事宜",
      "progress": "2026-01-21",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "8.1011",
      "supplier": "杭州利川机电有限公司",
      "manager": "陈赏",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州厂品管部留样室电梯维护保养申请事宜",
      "progress": "2026-03-10",
      "status": "已开工未完成",
      "dept": "品管",
      "cost": "0.52",
      "supplier": "苏州鑫安达电梯工程有限公司",
      "manager": "李本想",
      "Categories": "维修费",
      "Notes": "制程一科27.10.31结束，制程三科27.3.11结束"
    },
    {
      "name": "关于苏州顶津三车间主蒸汽管道补偿器汰换工程申请事宜",
      "progress": "2026-03-20",
      "status": "已开工未完成",
      "dept": "厂务",
      "cost": "9.6",
      "supplier": "上海重旗工程（集团）有限公司",
      "manager": "陈天飞",
      "Categories": "固定资产",
      "Notes": "已完成4个补偿器汰换，剩余2个未更换，因排产原因报备10月1日期间更换"
    },
    {
      "name": "关于苏州厂一三车间水站浓水回收节能改造邀标申请事宜",
      "progress": "2025-12-04",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "132",
      "supplier": "天津特立环保科技有限公司",
      "manager": "陈赏",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州厂无菌车间瓶胚直连改造申请事宜",
      "progress": "2026-02-13",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "6.26",
      "supplier": "上海久明科技有限公司",
      "manager": "徐杨",
      "Categories": "固定资产",
      "Notes": "未完成，目前程序调试中"
    },
    {
      "name": "关于申请吹瓶3线加热炉增加水冷招标事宜",
      "progress": "2026-03-07",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "3.15",
      "supplier": "上海秉元机电设备有限公司",
      "manager": "徐杨",
      "Categories": "维修费",
      "Notes": "使用效果确认中，无异常，8月验收"
    },
    {
      "name": "26年苏州顶津厂区土建类易损设施年度整改项目立项申请事宜",
      "progress": "2026-03-30",
      "status": "已开工未完成",
      "dept": "厂务",
      "cost": "18.1",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "郑胤煊",
      "Categories": "维修费",
      "Notes": "外围平台刷漆未完成"
    },
    {
      "name": "关于苏州顶津制造一处星巴克罐线漏水点改善申请事宜",
      "progress": "2026-03-03",
      "status": "已开工未完成",
      "dept": "星巴克",
      "cost": "1.95",
      "supplier": "杭州利川机电有限公司",
      "manager": "王天禄",
      "Categories": "维修费",
      "Notes": "项目还未完成"
    },
    {
      "name": "关于制造一处瓶胚塔水管更换申请事宜",
      "progress": "2026-03-19",
      "status": "已开工未完成",
      "dept": "制一",
      "cost": "6.9",
      "supplier": "武汉鑫得盛机电设备有限公司",
      "manager": "赵春军",
      "Categories": "维修费",
      "Notes": "已开工，分阶段施工"
    },
    {
      "name": "苏州顶津厂房屋面蒸汽排汽管改造项目立项申请事宜",
      "progress": "2026-04-13",
      "status": "已开工未完成",
      "dept": "厂务",
      "cost": "13",
      "supplier": "武汉鑫得盛机电设备有限公司",
      "manager": "郑胤煊",
      "Categories": "维修费",
      "Notes": "需结合停产时间处理排气管。材料预制已基本完成。"
    },
    {
      "name": "关于苏州厂无菌五六后段重新布局物料输送带改造议价申请事宜",
      "progress": "2026-04-23",
      "status": "已开工未完成",
      "dept": "设备",
      "cost": "44",
      "supplier": "阳兴造机（东莞）有限公司",
      "manager": "刘传海",
      "Categories": "固定资产"
    },
    {
      "name": "关于26年苏州顶津厂区外围土建改善小工程招标申请事宜 ",
      "progress": "2026-05-15",
      "status": "已开工未完成",
      "dept": "厂务",
      "cost": "29.92",
      "supplier": "苏州卓鼎建设工程有限公司",
      "manager": "郑胤煊",
      "Categories": "维修费",
      "Notes": "屋面不锈钢防坠网、二号门精神堡未修复"
    },
    {
      "name": "关于二/三车间土建项目改善申请招标事宜",
      "progress": "2026-04-29",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "27.8",
      "supplier": "安徽业峰建筑工程有限公司",
      "manager": "陈赏",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州厂制造二处生产线品质改善工程事宜（无菌+吹瓶部分）",
      "progress": "2026-05-12",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "11.96",
      "supplier": "杭州利川机电有限公司",
      "manager": "卞清泉",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州厂制造二处生产线品质改善工程事宜（调配部分）",
      "progress": "2026-05-12",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "12.18",
      "supplier": "武汉鑫得盛机电设备有限公司",
      "manager": "陈赏",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州厂无菌五六线线后段改造配套安装工程邀标申请事宜",
      "progress": "2026-06-03",
      "status": "已开工未完成",
      "dept": "设备",
      "cost": "85.8",
      "supplier": "创志建设工程（广东）有限公司",
      "manager": "刘传海",
      "Categories": "固定资产"
    },
    {
      "name": "关于26年苏州顶津天沟、女儿墙漏雨改善工程项目申请事宜",
      "progress": "2026-06-05",
      "status": "已开工未完成",
      "dept": "厂务",
      "cost": "82",
      "supplier": "北京京禹达建筑装饰集团有限公司",
      "manager": "郑胤煊",
      "Categories": "维修费",
      "Notes": "已完成三车间屋面女儿墙、天沟部分区域，试天气情况推进"
    },
    {
      "name": "关于苏州厂二、三车间增加萃取冰水板换节能改造邀标申请事宜",
      "progress": "2026-05-07",
      "status": "已开工未完成",
      "dept": "设备",
      "cost": "51.8",
      "supplier": "宋泰工程技术（杭州）有限公司",
      "manager": "刘传海",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州厂无菌六线新增套标机、贴标机、膜包机配套输送带改造邀标申请事宜",
      "progress": "2026-05-29",
      "status": "已开工未完成",
      "dept": "设备",
      "cost": "193.2",
      "supplier": "象山大宇机械设备有限公司",
      "manager": "刘传海",
      "Categories": "固定资产"
    },
    {
      "name": "26年苏州顶津充电桩加装及快递区域硬化小工程项目",
      "progress": "2026-07-08",
      "status": "已开工未完成",
      "dept": "厂务",
      "cost": "9.88",
      "supplier": "苏州驻阳机电设备工程有限公司",
      "manager": "郑胤煊",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州顶津内屋面&钢梁反吊顶及刷漆改善事宜",
      "progress": "2026-07-08",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "24.93",
      "supplier": "武汉鑫得盛机电设备有限公司",
      "manager": "李双",
      "Categories": "其他资产"
    },
    {
      "name": "关于苏州厂三车间岗位空调制冷改善邀标事宜",
      "progress": "2026-06-27",
      "status": "已开工未完成",
      "dept": "制二",
      "cost": "12.5",
      "supplier": "苏州振佑机电科技有限公司",
      "manager": "陈臣",
      "Categories": "维修费"
    },
    {
      "name": "苏州顶津一、三车间冷却塔风机升级改造立项申请",
      "progress": "2026-06-26",
      "status": "已开工未完成",
      "dept": "厂务",
      "cost": "49",
      "supplier": "南京欧世德机电科技发展有限公司",
      "manager": "孙士友",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州厂蒸汽管道保温汰换立项申请事宜（厂务+一车间）",
      "progress": "2026-07-03",
      "status": "已开工未完成",
      "dept": "厂务",
      "cost": "44.26",
      "supplier": "武汉鑫得盛机电设备有限公司",
      "manager": "陈天飞",
      "Categories": "其他资产"
    },
    {
      "name": "关于苏州顶津配电房空调汰换申请事宜",
      "progress": "2026-06-05",
      "status": "未开工未完成",
      "dept": "厂务",
      "cost": "29",
      "supplier": "苏州聚划算电器有限公司",
      "manager": "陈天飞",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州厂碱性水线物料输送带改造邀标申请事宜",
      "progress": "2026-06-15",
      "status": "未开工未完成",
      "dept": "设备",
      "cost": "14.07",
      "supplier": "苏州江泰智能科技有限公司",
      "manager": "刘传海",
      "Categories": "固定资产"
    },
    {
      "name": "关于苏州厂三车间配电变压器扩容招标申请事宜",
      "progress": "2026-06-29",
      "status": "未开工未完成",
      "dept": "厂务",
      "cost": "276",
      "supplier": "苏州华安普电力科技有限公司",
      "manager": "陈天飞",
      "Categories": "固定资产",
      "Notes": "预计8月6日进厂开始槽钢等施工制作"
    },
    {
      "name": "关于一车间水4线加装喷淋装置事宜",
      "progress": "2026-06-18",
      "status": "未开工未完成",
      "dept": "制一",
      "cost": "0.77",
      "supplier": "杭州利川机电有限公司",
      "manager": "朱鹏鹏",
      "Categories": "维修费"
    },
    {
      "name": "关于厂务处厌氧系统沼气管道铺设改造申请事宜",
      "progress": "2026-06-18",
      "status": "未开工未完成",
      "dept": "厂务",
      "cost": "4.7",
      "supplier": "杭州利川机电有限公司",
      "manager": "陈天飞",
      "Categories": "维修费"
    },
    {
      "name": "关于一车间充填三科现场改善工程招标申请事宜",
      "progress": "2026-07-08",
      "status": "未开工未完成",
      "dept": "制一",
      "cost": "8.31",
      "supplier": "杭州利川机电有限公司",
      "manager": "杨硕",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州顶津三车间瓶胚库快速门更换安装工程项目申请事宜",
      "progress": "2026-07-16",
      "status": "未开工未完成",
      "dept": "制二",
      "cost": "6.16",
      "supplier": "苏州玥祥建筑工程有限公司",
      "manager": "徐杨",
      "Categories": "维修费"
    },
    {
      "name": "关于无菌二线旋盖机保养配套龙门架工程申请事宜",
      "progress": "2026-07-23",
      "status": "未开工未完成",
      "dept": "制二",
      "cost": "1.71",
      "supplier": "杭州利川机电有限公司",
      "manager": "卞清泉",
      "Categories": "维修费"
    },
    {
      "name": "关于苏州厂蒸汽管道保温汰换立项申请事宜（三车间）",
      "progress": "2026-07-03",
      "status": "未开工未完成",
      "dept": "厂务",
      "cost": "40.64",
      "supplier": "杭州利川机电有限公司",
      "manager": "陈天飞",
      "Categories": "其他资产"
    },
    {
      "name": "关于苏州厂110KV变电站委外运营及10KV高压配电预防性保养招标申请事宜",
      "progress": "2026-07-03",
      "status": "未开工未完成",
      "dept": "厂务",
      "cost": "100",
      "supplier": "苏州华安普电力科技有限公司",
      "manager": "陈天飞",
      "Categories": "劳务费"
    },
    {
      "name": "关于CSD线汰换膜包机配套安装工程邀标申请事宜",
      "progress": "2026-07-16",
      "status": "未开工未完成",
      "dept": "设备",
      "cost": "13.51",
      "supplier": "武汉鑫得盛机电设备有限公司",
      "manager": "刘传海",
      "Categories": "固定资产"
    }
  ],
  "planProjectsData": [
    {
      "name": "瓶胚直连扩展",
      "category": "自动化改善",
      "status": "未开始",
      "currentStatus": "目前只连吹瓶一线，利用率低",
      "improvement": "增加连吹瓶二线或改为AGV直供",
      "cost": "35",
      "benefit": "15",
      "endTime": "2027-06-30",
      "progressDesc": "方案待评估，目前作业空间满足需要",
      "manager": "赵春军"
    },
    {
      "name": "直连补充瓶胚回温",
      "category": "品质改善",
      "status": "未开始",
      "currentStatus": "1、直连瓶胚到达吹瓶机温度约40度（不加空调降温）\r\r\n2、补充瓶胚冬天温度较低，工艺不稳定（温差超10度以上）",
      "improvement": "建立回温房间，对补充瓶胚进行回温",
      "endTime": "2027-09-15",
      "progressDesc": "方案规划中",
      "manager": "刘传海、赵春军"
    },
    {
      "name": "新增物料输送带",
      "category": "自动化改善",
      "status": "规划中",
      "currentStatus": "六连包机移入车间后投料不方便",
      "improvement": "TP1/2线规划物料输送带",
      "endTime": "2027-12-20",
      "progressDesc": "方案已拟定，待和制造讨论后7月份开始邀标作业",
      "manager": "刘传海、杨硕"
    },
    {
      "name": "汰换具备外箱覆膜功能的膜包机",
      "category": "自动化改善",
      "status": "规划中",
      "currentStatus": "膜包效果较差，品质不达标；不具备外箱覆膜能力",
      "improvement": "汰换膜包机，增加输送带具备外箱覆膜功能",
      "cost": "107",
      "endTime": "2027-06-30",
      "progressDesc": "招标作业中",
      "manager": "刘传海、乔欣欣"
    },
    {
      "name": "水3线具备康水能力",
      "category": "排产优化",
      "status": "未开始",
      "improvement": "具备1881瓶口550康水生产能力",
      "endTime": "2027-06-30",
      "progressDesc": "方案拟定中",
      "manager": "刘传海、王辉"
    },
    {
      "name": "550纯水乐生产能力",
      "category": "排产优化",
      "status": "规划中",
      "currentStatus": "二线产能不足，四线康水有富裕产能",
      "improvement": "具备纯水乐生产能力",
      "endTime": "2027-06-30",
      "manager": "房亚军、刘传海、王辉"
    },
    {
      "name": "调配冷凝水热能回收",
      "category": "节能降耗",
      "status": "采购中",
      "currentStatus": "一、二车间目前排地沟，三车间自流回冷凝水主管道，有水锤",
      "improvement": "增加缓冲罐回，及增压泵回主管道",
      "cost": "65",
      "benefit": "30",
      "endTime": "2027-06-30",
      "progressDesc": "招标作业中",
      "manager": "刘传海、王辉"
    },
    {
      "name": "UHT冷凝水热能回收",
      "category": "节能降耗",
      "status": "规划中",
      "currentStatus": "目前排放地沟",
      "improvement": "回收利用",
      "cost": "25",
      "benefit": "15",
      "endTime": "2027-06-30",
      "progressDesc": "水线已备货、罐线方案拟定中",
      "manager": "刘传海、王辉"
    },
    {
      "name": "膜包机入口自动化换产",
      "category": "自动化改善",
      "status": "未开始",
      "currentStatus": "散膜和外箱覆膜换产时间较长，而且入口调试稳定耗时耗力",
      "improvement": "增加升降装置",
      "cost": "15",
      "endTime": "2027-06-30",
      "progressDesc": "方案规划中",
      "manager": "朱鹏鹏、李双"
    },
    {
      "name": "增加自动加纸板机",
      "category": "自动化改善",
      "status": "采购中",
      "currentStatus": "每天浪费2个劳务",
      "improvement": "增加自动加纸板机",
      "cost": "30",
      "benefit": "15",
      "endTime": "2027-06-30",
      "progressDesc": "主机已核准，配套输送带及KHS对接信号等需要工厂自行规划",
      "manager": "杨华超"
    },
    {
      "name": "小袋糖自动化",
      "category": "自动化改善",
      "status": "未开始",
      "currentStatus": "6条线人工倒糖劳务浪费较大",
      "improvement": "增加机械手设备",
      "cost": "220",
      "benefit": "75",
      "endTime": "2027-06-30",
      "progressDesc": "方案已完成，待评估执行",
      "manager": "杨华超、刘传海"
    },
    {
      "name": "AGV搬运",
      "category": "自动化改善",
      "status": "规划中",
      "currentStatus": "2台瓶胚机每天2人拉瓶胚/斑",
      "improvement": "利用3台AGV替代4人拉胚，每班保留1人套袋整理铁框",
      "cost": "40",
      "benefit": "12.5",
      "endTime": "2027-06-30",
      "progressDesc": "立项签呈签核中，总部批注等沈阳结果，二次启动，方案需要修改，已预约厂商",
      "manager": "刘传海、杨华超"
    },
    {
      "name": "调配冷凝水回收利用",
      "category": "节能降耗",
      "status": "未开始",
      "currentStatus": "和生产线共用一根管道，小于生产线冷凝水压力，无法排出",
      "improvement": "管道改造，分开排放，淡季整改已规划，施工中，效果待验证",
      "cost": "8",
      "benefit": "10",
      "endTime": "2027-06-30",
      "progressDesc": "立项已核准，招标作业中"
    },
    {
      "name": "调配萃取冰水温度提升",
      "category": "节能降耗",
      "status": "施工中",
      "currentStatus": "萃取需要从65-75度降低到17度左右，板换设计要求9度冰水才能达到，造成整体冰水浪费（每升高1度可以节省约3%的电能）",
      "improvement": "增加冰水板换，提升冰水温度",
      "cost": "51",
      "benefit": "36",
      "endTime": "2027-06-30",
      "progressDesc": "立项签呈已完成，预计7月中旬到厂",
      "manager": "刘传海、陈赏"
    },
    {
      "name": "具备冰红、茉莉中包装生产能力",
      "category": "排产优化",
      "status": "未开始",
      "currentStatus": "目前生产1L和330规格，2条热充都1L换产产能损失较大",
      "improvement": "增加中包装品项生产能力",
      "cost": "170",
      "benefit": "55",
      "endTime": "2027-06-30",
      "progressDesc": "方案规划中",
      "manager": "刘传海、张军委、杨华超"
    },
    {
      "name": "防错系统及自动化搬运",
      "category": "自动化改善",
      "status": "规划中",
      "currentStatus": "新品多，工艺复杂，出错率增加",
      "improvement": "防错系统及自动化综合规划",
      "cost": "200",
      "benefit": "50",
      "endTime": "2027-06-30",
      "progressDesc": "方案规划中",
      "manager": "蒋城、陈赏"
    },
    {
      "name": "新增1台小UHT",
      "category": "节能降耗",
      "status": "规划中",
      "currentStatus": "前期新增小UHT无菌四线占用，无菌六线一直用大UHT，无菌五线及未来新增2.0品项",
      "improvement": "再新增两台台小UHT",
      "cost": "960",
      "benefit": "320",
      "endTime": "2027-06-30",
      "progressDesc": "方案已完成，待报备总部协助规划",
      "manager": "刘传海、张军委"
    },
    {
      "name": "机器人投物料",
      "category": "自动化改善",
      "status": "未开始",
      "currentStatus": "1、二、三车间劳务投物料，且有投错风险\r\r\n2、劳务费用较高，而且不固定",
      "endTime": "2027-06-30",
      "progressDesc": "方案规划中",
      "manager": "黄朗朗"
    },
    {
      "name": "瓶胚立体库",
      "category": "自动化改善",
      "status": "规划中",
      "currentStatus": "1、瓶胚库存能力不够，需要频繁移库；\r\r\n2、降温再加热浪费能源",
      "improvement": "建瓶胚立体库",
      "endTime": "2027-06-30",
      "progressDesc": "已完成，问题点待持续改善",
      "manager": "刘传海、徐杨"
    },
    {
      "name": "数采提升",
      "category": "自动化改善",
      "status": "未开始",
      "currentStatus": "水站、后段包装设备等无法自动采集，人工点检及调整控制",
      "improvement": "1、自行增加可采集的仪表\r\r\n2、和供应商一起开发采集系统",
      "endTime": "2027-06-30",
      "progressDesc": "方案规划中",
      "manager": "黄朗朗"
    },
    {
      "name": "萃取新增板换改造",
      "category": "节能降耗",
      "status": "施工中",
      "currentStatus": "萃取需要从65-75度降低到17度左右，板换设计要求9度冰水才能达到，造成整体冰水浪费（每升高1度可以节省约3%的电能）",
      "improvement": "增加冰水板换，提升冰水温度",
      "cost": "40",
      "benefit": "40",
      "endTime": "2027-06-30",
      "progressDesc": "立项已完成，招标作业中",
      "manager": "刘传海、陈赏"
    },
    {
      "name": "直连补充瓶胚回温",
      "category": "节能降耗",
      "status": "未开始",
      "currentStatus": "1、直连瓶胚到达吹瓶机温度约40度（不加空调降温）\r\r\n2、补充瓶胚冬天温度较低，工艺不稳定（温差超10度以上）",
      "endTime": "2027-06-30",
      "progressDesc": "与热泵技术一起规划，方案已交规划部审核",
      "manager": "魏志忠、刘传海"
    },
    {
      "name": "无菌3、4、6线在线糖度检测规划",
      "category": "节能降耗",
      "status": "施工中",
      "currentStatus": "人工检测浪费约1.4吨料液/次，无菌4、6线共计次CIP/年",
      "improvement": "增加在线检测糖度仪器",
      "cost": "52",
      "endTime": "2027-06-30",
      "progressDesc": "签呈已核准，改造件已到货，待找机会施工",
      "manager": "刘传海、张军委"
    },
    {
      "name": "330连线设备拆除",
      "category": "排产优化",
      "status": "未开始",
      "currentStatus": "设备占用大面积原料库，严重影响作业，计划10月份拆除",
      "improvement": "设备拆除，产能转至热充二线和无菌五线",
      "endTime": "2027-06-30",
      "progressDesc": "方案拟定中",
      "manager": "刘传海、陈赏"
    },
    {
      "name": "6条线洗瓶水回水",
      "category": "节能降耗",
      "status": "未开始",
      "currentStatus": "目前洗瓶水直接排放，6条线全部生产每天约600吨",
      "improvement": "增加水处理系统，处理后的水回收利用",
      "endTime": "2027-06-30",
      "progressDesc": "现场调研完成，方案已交总部立项",
      "manager": "刘彬、张军委、刘传海"
    },
    {
      "name": "高压机联动集控",
      "category": "节能降耗",
      "status": "未开始",
      "currentStatus": "各机台加载率根据设定值自动加卸载、系统无法判断合理性，无法自动进行开关机",
      "improvement": "增加集控，自动控制开关机数量",
      "endTime": "2027-06-30",
      "progressDesc": "方案拟定中",
      "manager": "孙士友、黄朗朗"
    },
    {
      "name": "三车间新增热泵评估",
      "category": "节能降耗",
      "status": "立项中",
      "currentStatus": "热充和无菌UHT蒸汽用量较大，可以规划节能",
      "improvement": "利用高温热泵技术",
      "endTime": "2027-06-30",
      "progressDesc": "现场调研完成，方案已交总部立项",
      "manager": "刘传海、孙士友"
    },
    {
      "name": "三车间8台低压机联动自控",
      "category": "节能降耗",
      "status": "备货中",
      "currentStatus": "目前单供且多为工频设备，需求端变化多",
      "improvement": "联动控制可节省11%电量",
      "cost": "23",
      "benefit": "32",
      "endTime": "2027-06-30",
      "progressDesc": "立项已核准，招标作业已完成，备货中",
      "manager": "刘传海、孙士友"
    },
    {
      "name": "新增变压器",
      "category": "排产优化",
      "status": "备货中",
      "currentStatus": "新增SCC和膜包品项，高配需增加变压器",
      "cost": "276",
      "endTime": "2027-06-30",
      "progressDesc": "立项签呈已核准，预计8月底到货",
      "manager": "陈天飞"
    },
    {
      "name": "智慧备件库",
      "category": "数字化",
      "status": "规划中",
      "currentStatus": "备件库人员减少，工作量极大，账务混乱",
      "improvement": "上智慧备件库",
      "cost": "175",
      "endTime": "2027-06-30",
      "progressDesc": "方案拟定中",
      "manager": "陈天飞"
    },
    {
      "name": "一车间自来水换热",
      "category": "节能降耗",
      "status": "规划中",
      "currentStatus": "塔水回水温度较高，热能浪费，且耗电冷却",
      "improvement": "与12水站自来水进行换热",
      "cost": "65",
      "benefit": "50",
      "endTime": "2027-06-30",
      "progressDesc": "方案拟定中",
      "manager": "刘传海、孙士友"
    },
    {
      "name": "二三车间高效机房",
      "category": "节能降耗",
      "status": "规划中",
      "currentStatus": "冰水机独立运行，且大部分增压泵无变频器，造成能源浪费",
      "improvement": "增加集控系统，做到自动调控",
      "cost": "480",
      "benefit": "170",
      "endTime": "2027-06-30",
      "progressDesc": "方案拟定中",
      "manager": "魏志忠，郑立虎、刘传海"
    },
    {
      "name": "RGV新增小车",
      "category": "排产优化",
      "status": "未开始",
      "currentStatus": "一车间3条线产品连廊移入二车间立体库，入库速度不足",
      "improvement": "新增1台小车",
      "cost": "17",
      "endTime": "2027-06-30",
      "progressDesc": "签呈签核中",
      "manager": "孙士友、黄朗朗"
    },
    {
      "name": "新增一跨5层四向车立体库",
      "category": "自动化改善",
      "status": "未开始",
      "currentStatus": "1、客制化产品现场管理难度大，客诉多\r\r\n2、一库库容不足",
      "cost": "750",
      "endTime": "2027-06-30",
      "progressDesc": "待旺季状况再评估",
      "manager": "汤平峰"
    },
    {
      "name": "WMS",
      "category": "自动化改善",
      "status": "规划中",
      "currentStatus": "泛得立体库目前不具备上线WMS系统，需要升级改造",
      "improvement": "1约15日到厂评估方案",
      "cost": "71",
      "endTime": "2027-06-30",
      "progressDesc": "持续配合学习",
      "manager": "袁胜利"
    },
    {
      "name": "外箱覆膜机无人化改善",
      "category": "自动化改善",
      "status": "未开始",
      "currentStatus": "目前人工放箱及码垛，0.3元/箱",
      "improvement": "移至三库连RGV直接入库",
      "endTime": "2027-06-30",
      "progressDesc": "方案拟定中",
      "manager": "黄朗朗"
    },
    {
      "name": "增加立体库",
      "category": "自动化改善",
      "status": "规划中",
      "currentStatus": "原料存放混乱且空间利用率底",
      "improvement": "1、二车间规划原料立体库\r\r\n2、三车间增加货架",
      "endTime": "2027-06-30",
      "progressDesc": "方案拟定中",
      "manager": "段春雷、黄朗朗"
    },
    {
      "name": "增加AGV倒库",
      "category": "自动化改善",
      "status": "规划中",
      "currentStatus": "散装车一车多库，旺季马路拥堵，出货能力不足",
      "endTime": "2027-06-30",
      "progressDesc": "方案拟定中",
      "manager": "黄晓飞、汤平峰、蒋城"
    }
  ],
  "assetData": [
    {
      "name": "UHT冷凝水热能回收",
      "category": "建筑材料",
      "dept": "基建工程部",
      "budget": "42,000,000",
      "actual": "31,000,000",
      "diff": "-26.2%",
      "month": "2026-10",
      "status": "正常"
    },
    {
      "name": "膜包机入口自动化换产",
      "category": "设备采购",
      "dept": "设备管理部",
      "budget": "35,000,000",
      "actual": "28,500,000",
      "diff": "-18.6%",
      "month": "2026-11",
      "status": "正常"
    },
    {
      "name": "增加自动加纸板机",
      "category": "物流智能化",
      "dept": "仓储物流部",
      "budget": "15,000,000",
      "actual": "12,800,000",
      "diff": "-14.7%",
      "month": "2026-12",
      "status": "正常"
    },
    {
      "name": "小袋糖自动化",
      "category": "公用设施",
      "dept": "动力能源部",
      "budget": "8,000,000",
      "actual": "8,200,000",
      "diff": "+2.5%",
      "month": "2026-09",
      "status": "预警"
    },
    {
      "name": "AGV搬运",
      "category": "物流智能化",
      "dept": "仓储物流部",
      "budget": "15,000,000",
      "actual": "12,800,000",
      "diff": "-14.7%",
      "month": "2026-12",
      "status": "正常"
    },
    {
      "name": "调配冷凝水回收利用",
      "category": "公用设施",
      "dept": "动力能源部",
      "budget": "8,000,000",
      "actual": "8,200,000",
      "diff": "+2.5%",
      "month": "2026-09",
      "status": "预警"
    },
    {
      "name": "调配萃取冰水温度提升",
      "category": "物流智能化",
      "dept": "仓储物流部",
      "budget": "15,000,000",
      "actual": "12,800,000",
      "diff": "-14.7%",
      "month": "2026-12",
      "status": "正常"
    },
    {
      "name": "具备冰红、茉莉中包装生产能力",
      "category": "公用设施",
      "dept": "动力能源部",
      "budget": "8,000,000",
      "actual": "8,200,000",
      "diff": "+2.5%",
      "month": "2026-09",
      "status": "预警"
    },
    {
      "name": "智能立库 AGV 转运机器人",
      "category": "物流智能化",
      "dept": "仓储物流部",
      "budget": "15,000,000",
      "actual": "12,800,000",
      "diff": "-14.7%",
      "month": "2026-12",
      "status": "正常"
    },
    {
      "name": "高效磁悬浮中央冷水机组",
      "category": "公用设施",
      "dept": "动力能源部",
      "budget": "8,000,000",
      "actual": "8,200,000",
      "diff": "+2.5%",
      "month": "2026-09",
      "status": "预警"
    }
  ]
};